sudo: required
services:
  - docker
before_install:
- docker build -t malinder2114/react-docker-script -f Dockerfile.dev .

script:
  - docker run malinder2114/react-docker-script npm run test -- --coverage
# this is a script to run tests
