sudo: required
services:
  - docker
before_install:
- docker build -t malinder2114/react-docker-script -f Dockerfile.dev .

script:
  - docker run -e CI=true malinder2114/react-docker-script npm run test
