sudo: required
services:
  - docker
before_install:
- docker build -t malinder2114/react-docker-script -f Dockerfile.dev .

script:
  - docker run -e CI=true malinder2114/react-docker-script npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-954364560751"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
